serviceConfig:
  scheme: http://
  hostName: localhost
  port: 4001
  path: /api/

databaseConfig:
  dbHostname: 0.0.0.0
  dbUsername: root
  dbPassword: mypassword
  dbPort: 6606
  dbDriver: com.mysql.cj.jdbc.Driver
  dbName: tippers_test
  dbSettings: ?autoReconnect=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=PST
