serviceConfig:
  scheme: http://
  hostName: localhost
  port: 4001
  path: /api/

databaseConfig:
  dbHostname: localhost
  dbUsername: user
  dbPassword: tippersrules
  dbPort: 3306
  dbDriver: com.mysql.cj.jdbc.Driver
  dbName: tippers_test
  dbSettings: ?autoReconnect=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=PST
