serviceConfig:
  scheme: http://
  hostName: localhost
  port: 4001
  path: /api/

databaseConfig:
  dbUsername: root
  dbPassword: mypassword
  dbHostname: 127.0.0.1
  dbPort: 6603
  dbDriver: com.mysql.cj.jdbc.Driver
  dbName: tippers_test
  dbSettings: ?autoReconnect=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=PST
